name: ed25519_edwards
description: A Dart implementation of ed25519, inspired by Go cryptography libraries.
version: 0.1.0
homepage: https://github.com/Tougee/ed25519

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
  hex: ^0.2.0
