name: ed25519_edwards
description: Dart port of ed25519 from Go Cryptography ed25519
version: 0.3.1
homepage: https://github.com/Tougee/ed25519

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  convert: ^3.0.0
  fixnum: ^1.0.0
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
  hex: ^0.2.0
  benchmark_harness: ^2.0.0
